const ActionTypes = {
    FETCH_POSITION_MASTER_DATA_START: 'FETCH_POSITION_MASTER_DATA_START',
    FETCH_POSITION_MASTER_DATA_SUCCESS: 'FETCH_POSITION_MASTER_DATA_SUCCESS',
    FETCH_POSITION_MASTER_DATA_FAIL: 'FETCH_POSITION_MASTER_DATA_FAIL',
}
export default ActionTypes;